### ISSUE TITLE
Idea: Investigate HTML Dialog Element for Modals

### ISSUE THREAD

**Issue by sbussard** [adam-sv/arc#2]
Benefits:
- Less styling and markup required
- Semantic Support
- Less react implementation overhead
- More fine grained control
- Automatic esc to close

Read more:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

**Comment by sbussard** [comment]
The approach I found valuable

Each component gets its own modals, and

1. remove default styling for dialog
```css
dialog {
  padding: 0;
  border: none;
  outline: none;
  background-color: transparent;
}
```

2. add custom styling
```scss
.SomeComponent {
  &-modal {
    padding: 2rem;
    border-radius: 1rem;
    background-color: var(--theme-bg-alt);

    &::backdrop {
      backdrop-filter: blur(1rem);
      background-color: var(--black);
    }
  }
}
```

3. useRef to access the dom
```typescript
const modalRef = useRef<HTMLDialogElement>(null);
```

```typescript
<dialog ref={modalRef} ... >
```

4. add a click handler to close when user clicks the backdrop
```typescript
function handleModalClick(event: MouseEvent<HTMLDialogElement>) {
  if (event.target === event.currentTarget) {
    event.currentTarget.close();
  }
}
```

```typescript
<dialog onClick={handleModalClick} ... >
```

5. trigger modal programmatically
```typescript
function handleSomethingClicked() {
  modalRef.current?.showModal();
}
```

There are two options for what to do from here
1. Use the return value of the modal (I'm not compelled)
2. Add a button inside the modal and use regular click handlers to do whatever action needs done
